# Generated by Django 4.1.5 on 2023-01-30 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('organisations', '0001_initial'), ('organisations', '0002_copy_org_type_data'), ('organisations', '0003_copy_org_data')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Organisation Types',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reference', models.IntegerField()),
                ('sort_code', models.IntegerField()),
                ('account_number', models.IntegerField()),
                ('postcode', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='', max_length=200)),
                ('organisation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisationtype')),
            ],
        ),
    ]
