# Generated by Django 4.1.5 on 2023-01-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            INSERT INTO organisations_organisationtype
            SELECT * FROM my_app_organisationtype;
            ''',
            reverse_sql=(
                '''
                INSERT INTO my_app_organisationtype
                SELECT * FROM organisations_organisationtype;
                '''
            ), elidable=True
        )
    ]
