# Generated by Django 4.1.5 on 2023-01-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_copy_org_type_data'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            INSERT INTO organisations_organisation
            SELECT * FROM my_app_organisation;
            ''',
            reverse_sql=(
                '''
                INSERT INTO my_app_organisation
                SELECT * FROM organisations_organisation;
                '''
            ), elidable=True
        )
    ]
