# Generated by Django 4.1.5 on 2023-01-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO buildings_region
            SELECT * FROM my_app_region;
        """, reverse_sql="""
            INSERT INTO my_app_region
            SELECT * FROM buildings_region;
        """, elidable=True)
    ]
