# Generated by Django 4.1.5 on 2023-01-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_copy_region_data'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO buildings_building
            SELECT * FROM my_app_building;
        """, reverse_sql="""
            INSERT INTO my_app_building
            SELECT * FROM buildings_building;
        """)
    ]
