# Generated by Django 4.1.5 on 2023-01-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='CashflowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cost Types',
            },
        ),
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('option', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('building', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cashflows.cashflowcategory')),
            ],
        ),
    ]
