# Generated by Django 4.1.5 on 2023-01-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_copy_account_type_data'), ('accounts', '0003_copy_hierarchy_data'), ('accounts', '0004_copy_account_data')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Account Types',
            },
        ),
        migrations.CreateModel(
            name='Hierarchy1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hierarchy2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('hierarchy1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.hierarchy1')),
            ],
        ),
        migrations.CreateModel(
            name='Hierarchy3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('hierarchy2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.hierarchy2')),
            ],
        ),
        migrations.CreateModel(
            name='Hierarchy4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('hierarchy3', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.hierarchy3')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.CharField(default='', max_length=50)),
                ('is_live', models.BooleanField(default=True, verbose_name='Live')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttype')),
                ('hierarchy4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hierarchy4')),
            ],
            options={
                'ordering': ('description',),
            },
        ),
    ]
