# Generated by Django 4.1.5 on 2023-01-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            INSERT INTO accounts_accounttype
            SELECT * FROM my_app_accounttype;
            ''',
            reverse_sql=(
                '''
                INSERT INTO my_app_accounttype
                SELECT * FROM accounts_accounttype;
                '''
            ),
            elidable=True
        ),
    ]
