# Generated by Django 4.1.5 on 2023-01-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_copy_hierarchy_data'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            INSERT INTO accounts_account
            (id, number, description, is_live, hierarchy4_id, account_type_id)
            SELECT id, number, description, is_live, hierarchy4_id,
            account_type_id FROM my_app_account
            ''',
            reverse_sql=(
                '''
                INSERT INTO accounts_account
                (id, number, description, is_live, hierarchy4_id,
                account_type_id)
                SELECT id, number, description, is_live, hierarchy4_id,
                account_type_id FROM my_app_account
                '''
            ),
            elidable=True
        )
    ]
