# Generated by Django 4.1.5 on 2023-01-18 09:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import invoice.validators


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('number', models.CharField(default='', max_length=50, verbose_name='Invoice Number')),
                ('date_issued', models.DateField(verbose_name='Date Issued')),
                ('pdf', models.FileField(blank=True, upload_to='issued-invoices/', verbose_name='PDF File')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid by customer')),
                ('associated_payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_app.contractpayment', verbose_name='Associated Payment')),
            ],
            options={
                'verbose_name_plural': 'Issued Invoices',
            },
        ),
        migrations.CreateModel(
            name='ReceivedInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='received-invoices/', validators=[invoice.validators.validate_is_pdf], verbose_name='PDF File')),
                ('date_received', models.DateField(verbose_name='Date Received')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('associated_payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_app.contractpayment', verbose_name='Associated Payment')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid by GPA')),
                ('number', models.CharField(default='', max_length=50, verbose_name='Invoice Number')),
            ],
            options={
                'verbose_name_plural': 'Received Invoices',
            },
        ),
    ]
