# Generated by Django 3.1.5 on 2021-04-07 10:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_delete_invoice'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='receivedinvoice',
            name='associated_payment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_app.contractpayment'),
        ),
        migrations.AddField(
            model_name='receivedinvoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
