# Generated by Django 3.1.5 on 2021-04-07 10:24

from django.db import migrations, models
import invoice.validators


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210407_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedinvoice',
            name='number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='receivedinvoice',
            name='pdf',
            field=models.FileField(upload_to='received-invoices/', validators=[invoice.validators.validate_is_pdf]),
        ),
    ]
