# Generated by Django 3.1.5 on 2021-04-07 10:48

from django.db import migrations, models
import django.db.models.deletion
import invoice.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_delete_invoice'),
        ('invoice', '0003_auto_20210407_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedinvoice',
            name='associated_payment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_app.contractpayment', verbose_name='Associated Payment'),
        ),
        migrations.AlterField(
            model_name='receivedinvoice',
            name='date_received',
            field=models.DateField(verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='receivedinvoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid by GPA'),
        ),
        migrations.AlterField(
            model_name='receivedinvoice',
            name='pdf',
            field=models.FileField(upload_to='received-invoices/', validators=[invoice.validators.validate_is_pdf], verbose_name='PDF File'),
        ),
    ]
