# Generated by Django 3.1.5 on 2021-04-13 14:58

from django.db import migrations, models
import invoice.validators


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20210413_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedinvoice',
            name='pdf',
            field=models.FileField(blank=True, upload_to='issued-invoices/', verbose_name='PDF File'),
        ),
        migrations.AlterField(
            model_name='receivedinvoice',
            name='pdf',
            field=models.FileField(upload_to='received-invoices/', validators=[invoice.validators.validate_is_pdf], verbose_name='PDF File'),
        ),
    ]
