# Generated by Django 4.1.5 on 2023-01-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedinvoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid by user'),
        ),
    ]
