# Generated by Django 3.1.5 on 2021-03-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_contractpayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='treatment',
            field=models.CharField(blank=True, choices=[('Lessee', 'Lessee'), ('Lessor', 'Lessor')], max_length=50, null=True, verbose_name='Treatment'),
        ),
    ]
