# Generated by Django 4.1.5 on 2023-01-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_update_org_fk_references'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='OrganisationType',
        ),
    ]
