# Generated by Django 4.1.5 on 2023-01-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_copy_account_data'),
        ('my_app', '0003_alter_transactiongroup_options_alter_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierarchy2',
            name='hierarchy1',
        ),
        migrations.RemoveField(
            model_name='hierarchy3',
            name='hierarchy2',
        ),
        migrations.RemoveField(
            model_name='hierarchy4',
            name='hierarchy3',
        ),
        migrations.AlterModelOptions(
            name='transactiongroup',
            options={'verbose_name_plural': 'Entry Groups'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='pseudoentry',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.DeleteModel(
            name='Hierarchy1',
        ),
        migrations.DeleteModel(
            name='Hierarchy2',
        ),
        migrations.DeleteModel(
            name='Hierarchy3',
        ),
        migrations.DeleteModel(
            name='Hierarchy4',
        ),
    ]
