# Generated by Django 3.1.5 on 2021-04-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20210324_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
