# Generated by Django 4.1.5 on 2023-01-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_copy_building_data'),
        ('my_app', '0004_delete_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='building',
            field=models.ManyToManyField(blank=True, to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='building',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
    ]
