# Generated by Django 4.1.5 on 2023-01-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_copy_building_data'),
        ('my_app', '0005_update_fk_references'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
